<a href="https://colab.research.google.com/github/busung/ML-DL_with_torch/blob/main/1_Tensor_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

# Numpy

In [ ]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
b = np.array([[0.,1.,2.,3.,4.,5.,6.],
              [0.,1.,2.,3.,4.,5.,6.]])
a = np.array([[[0.,1.,2.,3.,4.,5.,6.],
              [0.,1.,2.,3.,4.,5.,6.]]])
print(t)
print(b)
print(a)

[0. 1. 2. 3. 4. 5. 6.]
[[0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]]
[[[0. 1. 2. 3. 4. 5. 6.]
  [0. 1. 2. 3. 4. 5. 6.]]]


In [ ]:
print(t.ndim,b.ndim,a.ndim)# 말 그대로 차원
print(t.shape,b.shape,a.shape)#행 렬 순

(7,) (2, 7) (1, 2, 7)


In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


# Torch

In [ ]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])#Float 형식의 텐서 생산
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])# 1열만 다 가져와라
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting
* 다른 크기의 텐서를 연산하게 해 줌
* 자동적으로 적용되기에 주의해야 함

In [ ]:
m1 = torch.FloatTensor([[3,2]])
m2 = torch.FloatTensor([[2,1]])

In [ ]:
print(m1+m2)

tensor([[5., 3.]])


In [ ]:
#Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3->[[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [ ]:
# 2*1 vector + 1*2 vector
m1 = torch.FloatTensor([[1,2]]) # 2*1 -> 2*2 ([[1,2],[1,2]])
m2 = torch.FloatTensor([[3],[4]]) # 1*2 -> 2*2 ([[3,3],[4,4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


## Multiplicaiton VS Matrix Multiplication

In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print(m1*m2)#Broad Casting이 일어난 상태로 Cross Product 수행
print(m1.matmul(m2))#행렬 곱 연산 수행 (2*2 * 2*1 => 2*1)

tensor([[1., 2.],
        [6., 8.]])
tensor([[ 5.],
        [11.]])


## Mean/Sum/Max/Argmax
* Float에 대해서만 가능(Mean)
* dim = Shape의 순서대로 그 기준에 맞는 대상을 없애도록 평균/합/최대값을 구함
  * 2차원에선 (행,열) => dim = 0 행을 없애는 방향으로 구한다고 생각하면 됨

* Argmax: 행 혹은 열에서 가장 큰 값의 인덱스를 반환 (Max에서 값이 같이 반환됨)

In [ ]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [ ]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim=0))#행을 없애는 방향이므로 1*2의 행렬이 만들어짐
print(t.mean(dim=1))#열을 없애는 방향이므로 2*1의 행렬이 만들어져야 하지만 벡터이므로 밑에처럼 표현
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [ ]:
print(t.max(dim=0)[0])#arg랑 같이 반환 [0]이면 max값 [1]이면 arg
print(t.max(dim=0)[1])

tensor([3., 4.])
tensor([1, 1])


## View(=Reshape)
* Tensor의 Shape를 변경시키는 함수
* -1은 자동으로 지정해 달라는 뜻

In [ ]:
t = np.array([[[0,1,2],
               [3,4,5]],
              
              [[6,7,8],
               [9,10,11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze
* Shape의 element가 1인 경우 해당 층을 제거함

In [ ]:
ft= torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
#0번째 차원이 3이기에 Squeeze가 통하지 않음
print(ft.squeeze(dim=0))
print(ft.squeeze(dim=0).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
#1번째 차원이 1이기에 Squeeze가 통함
print(ft.squeeze(dim=1))
print(ft.squeeze(dim=1).shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze
* Squeeze를 해제

In [ ]:
ft= torch.FloatTensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting
* Tensor의 Type을 변경

In [ ]:
ft= torch.LongTensor([0,1,2])
ft

tensor([0, 1, 2])

In [ ]:
ft.float()

tensor([0., 1., 2.])

## Concatenate
* Tensor 두 개를 결합할 때

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [ ]:
print(torch.cat([x, y], dim=0))#행에 대해서 더 해라
print(torch.cat([x, y], dim=1))#열에 대해서 더 해라

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking
* tensor들을 쌓는 함수
* concat을 쉽게 해주네

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [ ]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
print(torch.cat([x,y,z], dim=0))
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)], dim=0))

tensor([1., 4., 2., 5., 3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros
* Ones_like: Shape은 같지만 값이 모두 0인 Tensor
* Zeros_liks: 이하 동문이지만 모두 1인 Tensor
* CPU,GPU Device 역시 똑같은 곳에 생성됨

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


## In-place Operation
* Tensor의 각 Elment에 연산을 취해 주는 함수
* _를 붙이면 replace됨

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
