<a href="https://colab.research.google.com/github/busung/ML-DL_with_torch/blob/main/5_Loading_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import torch.nn as nn
from torch import optim
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [12]:
class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = [[73,80,75],
                    [93,88,93],
                    [89,91,90],
                    [96,98,100],
                    [73,66,70]]

    self.y_data = [[152],[185],[180],[196],[142]]

  def __len__(self):#총 데이터의 양을 반환
    return len(self.x_data)

  def __getitem__(self,idx):#index가 주어지면 해당되는 데이터 값을 반환

    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])

    return x,y
  
dataset = CustomDataset()

In [13]:
dataloader = DataLoader(
    dataset,
    batch_size=2,#minibatch 학습을 진행 보통 2의 제곱수로 지정함
    shuffle=True
)

In [23]:
class MultiRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self,x):
    return self.linear(x)

In [27]:
model = MultiRegressionModel()
optimizer = optim.SGD(model.parameters(),lr=1e-5)

nb_epochs = 20

for epoch in range(0,nb_epochs+1):
  for batch_idx,samples in enumerate(dataloader):#dataloader는 x,y값을 튜플로 반환
    x_train,y_train = samples#튜플로 반환되어 있기에 이런 식으로 가능
    prediction = model(x_train)
    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 5 ==0:
      print("Epoch={} batch={}, cost={:4f}".format(epoch,batch_idx+1,cost.item()))

Epoch=0 batch=1, cost=32012.929688
Epoch=0 batch=2, cost=10211.826172
Epoch=0 batch=3, cost=3944.373291
Epoch=5 batch=1, cost=1.333963
Epoch=5 batch=2, cost=1.287937
Epoch=5 batch=3, cost=5.839049
Epoch=10 batch=1, cost=0.496269
Epoch=10 batch=2, cost=3.818032
Epoch=10 batch=3, cost=0.633357
Epoch=15 batch=1, cost=0.168914
Epoch=15 batch=2, cost=0.630896
Epoch=15 batch=3, cost=6.834583
Epoch=20 batch=1, cost=1.756002
Epoch=20 batch=2, cost=3.397780
Epoch=20 batch=3, cost=0.053271


In [26]:
#dataloader을 출력값
for batch_idx,samples in enumerate(dataloader):
  x_train,y_train = samples
  print(x_train)
  print(y_train)

tensor([[89., 91., 90.],
        [93., 88., 93.]])
tensor([[180.],
        [185.]])
tensor([[73., 80., 75.],
        [73., 66., 70.]])
tensor([[152.],
        [142.]])
tensor([[ 96.,  98., 100.]])
tensor([[196.]])
